@startuml
title Activity-диаграмма покупки цифрового товара
start
:Открыть каталог;
:Найти и выбрать товар;
:Открыть карточку товара;

if (Пользователь авторизован?) then (нет)
  :Перейти на страницу входа;
  :Получить JWT;
endif

if (Товар уже приобретён?) then (да)
  :Показать кнопку скачивания;
else (нет)
  :Добавить товар в корзину\nили купить сразу;
  :Создать Order;
  if (Заказ создан?) then (да)
    :Показать товар в разделе\n«Мои покупки»;
  else (нет)
    :Показать сообщение об ошибке;
    stop
  endif
endif

:Запросить /orders/{id}/download/;
:Проверить принадлежность заказа;
:Увеличить счётчик downloads;
:Сформировать TXT-файл\nс названием товара;
:Передать файл браузеру;
stop
@enduml
